#!/usr/bin/env python3
"""从中文图鉴文案生成 LVGL 9 的 14px 4bpp 子集字体(chinese_14)。

收录 CJK / 全角标点以及 ASCII(数字与英文界面),避免回落到偏细的
Montserrat。默认字体:macOS Hiragino Sans GB W6,并做轻微轮廓加粗,
让 240x320 屏上的白字不发虚。
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from ctypes import byref

OUT_C = "main/chinese_14.c"
OUT_H = "main/chinese_14.h"
STATIC_C = "main/pokedex_static.c"

UI_CHARS = (
    "图鉴查找跳号跳到编号输入编号已见身高体重确定打开叫声选择返回"
    "暂无图像"
    "长按双击中英世代上下改位按字母母"
    "虫恶龙电妖精格斗火飞行幽灵草地面冰一般毒超能岩石钢水"
    "第"
    "·、。！？「」—…（）"
)

# 生成器写入的中文字段
RE_QUOTED = re.compile(r'"((?:\\.|[^"\\])*)"')


def collect_chars(static_c: str) -> list[int]:
    cps: set[int] = set(range(0x20, 0x7F))  # ASCII,含数字与英文界面
    for ch in UI_CHARS:
        o = ord(ch)
        if o >= 0x80:
            cps.add(o)
    if os.path.isfile(static_c):
        text = open(static_c, encoding="utf-8").read()
        for m in RE_QUOTED.finditer(text):
            raw = m.group(1).replace("\\\\", "\\").replace('\\"', '"')
            for ch in raw:
                o = ord(ch)
                if o >= 0x80:
                    cps.add(o)
    return sorted(cps)


def pack_a4(gray: list[int], w: int, h: int) -> bytes:
    out = bytearray()
    for y in range(h):
        row = gray[y * w : (y + 1) * w]
        x = 0
        while x < w:
            hi = (row[x] >> 4) & 0x0F
            lo = (row[x + 1] >> 4) & 0x0F if x + 1 < w else 0
            out.append((hi << 4) | lo)
            x += 2
    return bytes(out)


def boost_coverage(buf: list[int], gamma: float) -> list[int]:
    if gamma == 1.0 or not buf:
        return buf
    out = []
    for g in buf:
        v = (g / 255.0) ** gamma
        out.append(min(255, int(v * 255.0 + 0.5)))
    return out


def render_glyphs(
    font_path: str,
    face_index: int,
    cps: list[int],
    px: int,
    embolden: int,
    gamma: float,
):
    try:
        from freetype import (
            Face,
            FT_GLYPH_FORMAT_OUTLINE,
            FT_LOAD_DEFAULT,
            FT_LOAD_NO_BITMAP,
            FT_LOAD_TARGET_NORMAL,
            FT_Outline_Embolden,
            FT_RENDER_MODE_NORMAL,
        )
    except ImportError as e:
        raise SystemExit(f"需要 freetype-py: pip install freetype-py ({e})") from e

    face = Face(font_path, index=face_index)
    face.set_char_size(px * 64)
    asc = int(round(face.size.ascender / 64.0))
    desc = int(round(-face.size.descender / 64.0))
    line_height = max(px + 2, asc + desc)
    base_line = max(2, desc)

    glyphs = []
    bitmaps = bytearray()
    bitmaps.extend(b"")  # glyph 0 无位图
    dsc = [dict(bitmap_index=0, adv_w=0, box_w=0, box_h=0, ofs_x=0, ofs_y=0)]

    for cp in cps:
        face.load_char(
            chr(cp),
            FT_LOAD_DEFAULT | FT_LOAD_NO_BITMAP | FT_LOAD_TARGET_NORMAL,
        )
        if embolden > 0 and face.glyph.format == FT_GLYPH_FORMAT_OUTLINE:
            FT_Outline_Embolden(byref(face.glyph.outline._FT_Outline), embolden)
        face.glyph.render(FT_RENDER_MODE_NORMAL)
        slot = face.glyph
        bmp = slot.bitmap
        w, h = bmp.width, bmp.rows
        buf = list(bmp.buffer) if w and h else []
        buf = boost_coverage(buf, gamma)
        packed = pack_a4(buf, w, h) if buf else b""
        adv = max(0, slot.advance.x // 4)  # 26.6 → 8.4
        if embolden > 0:
            adv += embolden // 4
        if adv > 4095:
            adv = 4095
        dsc.append(
            dict(
                bitmap_index=len(bitmaps),
                adv_w=adv,
                box_w=w,
                box_h=h,
                ofs_x=slot.bitmap_left,
                ofs_y=slot.bitmap_top - h,
            )
        )
        bitmaps.extend(packed)
        glyphs.append(cp)

    return glyphs, dsc, bytes(bitmaps), line_height, base_line


def c_bytes(data: bytes, per_line: int = 12) -> str:
    parts = []
    for i in range(0, len(data), per_line):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + per_line])
        parts.append(f"    {chunk},")
    return "\n".join(parts)


def write_font(
    out_c: str,
    out_h: str,
    glyphs: list[int],
    dsc,
    bitmap: bytes,
    line_height: int,
    base_line: int,
) -> None:
    if not glyphs:
        raise SystemExit("没有可生成的中文字形")

    first, last = glyphs[0], glyphs[-1]
    rel = [cp - first for cp in glyphs]
    if last - first + 1 > 0xFFFF:
        raise SystemExit("Unicode 跨度过大,需要拆 cmap")

    lines = [
        "/* Auto-generated by tools/gen_pokedex_font.py. Do not edit. */",
        '#include "chinese_14.h"',
        "",
        "static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {",
        c_bytes(bitmap) if bitmap else "    0x00,",
        "};",
        "",
        "static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {",
    ]
    for g in dsc:
        lines.append(
            "    {.bitmap_index = %d, .adv_w = %d, .box_w = %d, .box_h = %d, "
            ".ofs_x = %d, .ofs_y = %d},"
            % (g["bitmap_index"], g["adv_w"], g["box_w"], g["box_h"], g["ofs_x"], g["ofs_y"])
        )
    lines += [
        "};",
        "",
        "static const uint16_t unicode_list_0[] = {",
    ]
    for i in range(0, len(rel), 8):
        lines.append("    " + ", ".join(str(x) for x in rel[i : i + 8]) + ",")
    lines += [
        "};",
        "",
        "static const lv_font_fmt_txt_cmap_t cmaps[] = {",
        "    {",
        f"        .range_start = {first}, .range_length = {last - first + 1},",
        "        .glyph_id_start = 1, .unicode_list = unicode_list_0,",
        "        .glyph_id_ofs_list = NULL,",
        f"        .list_length = {len(rel)},",
        "        .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY",
        "    }",
        "};",
        "",
        "static const lv_font_fmt_txt_dsc_t font_dsc = {",
        "    .glyph_bitmap = glyph_bitmap,",
        "    .glyph_dsc = glyph_dsc,",
        "    .cmaps = cmaps,",
        "    .kern_dsc = NULL,",
        "    .kern_scale = 0,",
        "    .cmap_num = 1,",
        "    .bpp = 4,",
        "    .kern_classes = 0,",
        "    .bitmap_format = 0,",
        # LVGL 9: stride=0 表示整幅连续打包。pack_a4 每行按字节对齐,
        # 奇数宽汉字必须 stride=1,否则花屏。
        "    .stride = 1,",
        "};",
        "",
        "const lv_font_t chinese_14 = {",
        "    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,",
        "    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,",
        f"    .line_height = {line_height},",
        f"    .base_line = {base_line},",
        "    .subpx = LV_FONT_SUBPX_NONE,",
        "    .underline_position = -1,",
        "    .underline_thickness = 1,",
        "    .dsc = &font_dsc,",
        "    .fallback = &lv_font_montserrat_14,",
        "    .static_bitmap = 1,",
        "};",
        "",
    ]
    os.makedirs(os.path.dirname(out_c) or ".", exist_ok=True)
    with open(out_c, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    with open(out_h, "w", encoding="utf-8") as f:
        f.write(
            "/* Auto-generated by tools/gen_pokedex_font.py. Do not edit. */\n"
            "#pragma once\n"
            "#include \"lvgl.h\"\n"
            "extern const lv_font_t chinese_14;\n"
        )


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--font", default="/System/Library/Fonts/Hiragino Sans GB.ttc")
    ap.add_argument("--face", type=int, default=2, help="Hiragino Sans GB W6")
    ap.add_argument("--size", type=int, default=14)
    ap.add_argument(
        "--embolden",
        type=int,
        default=48,
        help="FreeType 轮廓加粗,单位 26.6(48≈0.75px)",
    )
    ap.add_argument(
        "--gamma",
        type=float,
        default=0.55,
        help="覆盖率伽马<1 让浅灰更实,减轻发虚",
    )
    ap.add_argument("--static-c", default=STATIC_C)
    ap.add_argument("-o", default=OUT_C)
    ap.add_argument("--header", default=OUT_H)
    args = ap.parse_args()

    cps = collect_chars(args.static_c)
    print(f"字形 {len(cps)} 个,字体 {args.font} face {args.face}")
    glyphs, dsc, bitmap, line_height, base_line = render_glyphs(
        args.font, args.face, cps, args.size, args.embolden, args.gamma
    )
    write_font(args.o, args.header, glyphs, dsc, bitmap, line_height, base_line)
    print(f"  {args.o}: bitmap {len(bitmap)} B, glyphs {len(glyphs)}")
    print(f"  line_height {line_height} base_line {base_line}")
    print(f"  {args.header}")


if __name__ == "__main__":
    main()
